# Generated by Django 4.2.7 on 2025-09-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ElevateAI', '0002_rename_fields_to_match_nodejs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicdetails',
            name='profilePicture',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='githubLink',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='project',
            name='liveUrl',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
